# -*- coding: utf-8 -*-
"""
CAWS Pet Adoption System - Real-Time Pet Recommendation Engine
Algorithm  : Random Forest Classifier (Trained) + Multi-Attribute Scoring Engine
Framework  : Scikit-Learn, Pandas, NumPy, Joblib
Model File : ml/pet_match_model.pkl  (generated by ml/train_model.py)

Weighting Distribution:
  - Coat Color Match            : 22% (Primary Demographics)
  - Age Group Match             : 20% (Primary Demographics)
  - Gender Match                : 20% (Primary Demographics)
  - Temperament Cosine Sim      : 19% (Behavioral Alignment)
  - Adopter Capability/Lifestyle: 19% (Living, Space, Routine, Special Care)
  Total Demographics = 62% > Temperament & Capability = 38%
"""

import os
import sys

# Ensure ML packages are always found
_user_site = os.path.join(os.path.expanduser('~'),
                          'AppData', 'Roaming', 'Python', 'Python314', 'site-packages')
if _user_site not in sys.path:
    sys.path.insert(0, _user_site)

import json
import joblib
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# ---------------------------------------------------------
# Constants & Color Families
# ---------------------------------------------------------
ALL_TEMPERAMENT_TAGS = [
    'Friendly', 'Calm', 'Energetic', 'Shy',
    'Playful', 'Independent', 'Affectionate', 'Protective'
]

TAG_INDEX = {t: i for i, t in enumerate(ALL_TEMPERAMENT_TAGS)}

COLOR_FAMILIES = {
    'orange': ['orange', 'ginger', 'red', 'yellow', 'gold'],
    'black': ['black', 'dark', 'charcoal'],
    'white': ['white', 'cream', 'ivory', 'light'],
    'brown': ['brown', 'tan', 'chocolate', 'fawn', 'buff', 'cocoa'],
    'tricolor': ['tricolor', 'calico', 'tortie', 'torbie', 'multi'],
    'gray': ['gray', 'grey', 'silver', 'blue', 'smoke'],
    'tabby': ['tabby', 'striped', 'brindle', 'tiger'],
}

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH    = os.path.join(SCRIPT_DIR, 'pet_match_model.pkl')
FEATURES_PATH = os.path.join(SCRIPT_DIR, 'feature_columns.json')

# ---------------------------------------------------------
# Load trained model
# ---------------------------------------------------------
_trained_model   = None
_feature_columns = None

def _load_model():
    global _trained_model, _feature_columns
    if _trained_model is None and os.path.exists(MODEL_PATH) and os.path.exists(FEATURES_PATH):
        try:
            _trained_model   = joblib.load(MODEL_PATH)
            with open(FEATURES_PATH, 'r', encoding='utf-8') as f:
                _feature_columns = json.load(f)
        except Exception as e:
            _trained_model   = None
            _feature_columns = None
    return _trained_model, _feature_columns


# ---------------------------------------------------------
# Matching Helpers
# ---------------------------------------------------------
def _parse_age_category(age_str):
    if not isinstance(age_str, str):
        return 'adult'
    s = age_str.lower().strip()
    if any(k in s for k in ['day', 'week', 'month', '0 year', '0 years', 'puppy', 'kitten', '< 1']):
        return 'kitten_puppy'
    elif any(k in s for k in ['1 year', '2 year', 'young', 'junior']):
        return 'young'
    elif any(k in s for k in ['8 year', '9 year', '10 year', '11 year', '12 year', 'senior', 'old']):
        return 'senior'
    return 'adult'


def _match_color(pref_col, pet_color):
    pref = str(pref_col or 'any').lower().strip()
    if pref in ['any', 'all', '', 'any color']:
        return 1.0
    
    pet_col = str(pet_color or '').lower().strip()
    if not pet_col:
        return 0.5
    
    if pref in pet_col or pet_col in pref:
        return 1.0
    
    for family, aliases in COLOR_FAMILIES.items():
        pref_in_family = any(a in pref for a in aliases) or family in pref
        pet_in_family = any(a in pet_col for a in aliases) or family in pet_col
        if pref_in_family and pet_in_family:
            return 1.0
            
    if '/' in pet_col or '-' in pet_col:
        parts = pet_col.replace('-', '/').split('/')
        for part in parts:
            part = part.strip()
            if part in pref or pref in part:
                return 0.75
            for family, aliases in COLOR_FAMILIES.items():
                if any(a in pref for a in aliases) and any(a in part for a in aliases):
                    return 0.75

    return 0.0


def _match_age(pref_age, pet_age_cat):
    pref = str(pref_age or 'any').lower().strip()
    if pref in ['any', 'all', '', 'any age']:
        return 1.0
    
    if any(k in pref for k in ['puppy', 'kitten', '< 1', 'kitten_puppy']):
        p_cat = 'kitten_puppy'
    elif any(k in pref for k in ['young', '1 - 3', 'junior']):
        p_cat = 'young'
    elif any(k in pref for k in ['senior', '8+', 'old']):
        p_cat = 'senior'
    else:
        p_cat = 'adult'
        
    if p_cat == pet_age_cat:
        return 1.0
    
    adjacency = {
        'kitten_puppy': ['young'],
        'young': ['kitten_puppy', 'adult'],
        'adult': ['young', 'senior'],
        'senior': ['adult'],
    }
    if pet_age_cat in adjacency.get(p_cat, []):
        return 0.4
    return 0.0


def _match_gender(pref_gender, pet_gender):
    pref = str(pref_gender or 'any').lower().strip()
    if pref in ['any', 'all', '', 'any gender']:
        return 1.0
    
    pet_g = str(pet_gender or '').lower().strip()
    if not pet_g or pet_g == 'unknown':
        return 0.5
    
    if pref == 'male' and ('male' in pet_g and 'female' not in pet_g):
        return 1.0
    if pref == 'female' and 'female' in pet_g:
        return 1.0
    return 0.0


# ---------------------------------------------------------
# Feature Engineering
# ---------------------------------------------------------
def _build_feature_row(adopter_profile, pet):
    if not isinstance(adopter_profile, dict):
        adopter_profile = {}

    living   = str(adopter_profile.get('living_environment', 'apartment')).lower()
    activity = str(adopter_profile.get('activity_level', 'moderate')).lower()
    exp      = str(adopter_profile.get('pet_experience', 'first_time')).lower()
    has_kids = int(bool(adopter_profile.get('has_children', False)))
    has_pets = int(bool(adopter_profile.get('has_other_pets', False)))
    hours    = str(adopter_profile.get('hours_alone', '4_7')).lower()
    sp_cap   = int(bool(adopter_profile.get('special_care_capacity', False) or adopter_profile.get('special_care_capability', False)))
    
    pref_col    = str(adopter_profile.get('preferred_color', 'any')).lower()
    pref_age    = str(adopter_profile.get('preferred_age', 'any')).lower()
    pref_gender = str(adopter_profile.get('preferred_gender', 'any')).lower()

    desired_tags_list = [t for t in adopter_profile.get('desired_temperaments', [])
                         if t in ALL_TEMPERAMENT_TAGS]
    desired_vec = [1 if t in desired_tags_list else 0 for t in ALL_TEMPERAMENT_TAGS]

    # Pet side
    species  = str(pet.get('type', 'dog')).lower()
    age_raw  = str(pet.get('age', 'adult')).lower()
    age_cat  = _parse_age_category(age_raw)
    color    = str(pet.get('color', '')).lower()
    gender   = str(pet.get('gender', 'unknown')).lower()
    med_hist = str(pet.get('medical_history', '')).lower()
    sp_need  = int(any(k in med_hist for k in ['special', 'chronic', 'amputee', 'blind', 'deaf', 'disabilit']))

    pet_tags_list = [t for t in pet.get('temperaments', []) if t in ALL_TEMPERAMENT_TAGS]
    pet_vec = [1 if t in pet_tags_list else 0 for t in ALL_TEMPERAMENT_TAGS]

    # Match Scores
    color_match_score  = _match_color(pref_col, color)
    age_match_score    = _match_age(pref_age, age_cat)
    gender_match_score = _match_gender(pref_gender, gender)

    # Tag similarity
    d_arr = np.array(desired_vec, dtype=float)
    p_arr = np.array(pet_vec, dtype=float)
    d_mag = np.linalg.norm(d_arr)
    p_mag = np.linalg.norm(p_arr)
    tag_sim = float(np.dot(d_arr, p_arr) / (d_mag * p_mag)) if d_mag > 0 and p_mag > 0 else 0.50

    # Lifestyle suitability
    lifestyle_pts = 0.60
    if 'apartment' in living:
        if species == 'cat' or ('Calm' in pet_tags_list or 'Independent' in pet_tags_list):
            lifestyle_pts += 0.20
        elif species == 'dog' and 'Energetic' in pet_tags_list:
            lifestyle_pts -= 0.20
    elif 'yard' in living:
        if 'Energetic' in pet_tags_list or 'Playful' in pet_tags_list:
            lifestyle_pts += 0.20

    if activity in ['high', 'active'] and ('Energetic' in pet_tags_list or 'Playful' in pet_tags_list):
        lifestyle_pts += 0.15
    elif activity == 'relaxed' and 'Calm' in pet_tags_list:
        lifestyle_pts += 0.15

    if exp == 'first_time':
        if 'Friendly' in pet_tags_list or 'Calm' in pet_tags_list:
            lifestyle_pts += 0.10
        if 'Protective' in pet_tags_list:
            lifestyle_pts -= 0.15

    if has_kids and ('Friendly' in pet_tags_list or 'Playful' in pet_tags_list):
        lifestyle_pts += 0.10
    if has_pets and ('Friendly' in pet_tags_list or 'Playful' in pet_tags_list):
        lifestyle_pts += 0.10

    if hours in ['8_plus', '8+', '8plus']:
        if 'Independent' in pet_tags_list or 'Calm' in pet_tags_list:
            lifestyle_pts += 0.15
        if age_cat == 'kitten_puppy':
            lifestyle_pts -= 0.25
    elif hours in ['0_3', '0-3']:
        if 'Affectionate' in pet_tags_list or age_cat == 'kitten_puppy':
            lifestyle_pts += 0.15

    if sp_need:
        lifestyle_pts += 0.25 if sp_cap else -0.35

    lifestyle_normalized = min(1.0, max(0.0, lifestyle_pts))

    row = {
        'color_matched'            : round(float(color_match_score), 4),
        'age_matched'              : round(float(age_match_score), 4),
        'gender_matched'           : round(float(gender_match_score), 4),
        'is_dog'                   : int(species == 'dog'),
        'is_cat'                   : int(species == 'cat'),
        'pet_age_kitten_puppy'     : int(age_cat == 'kitten_puppy'),
        'pet_age_young'            : int(age_cat == 'young'),
        'pet_age_adult'            : int(age_cat == 'adult'),
        'pet_age_senior'           : int(age_cat == 'senior'),
        'pet_is_male'              : int('male' in gender and 'female' not in gender),
        'pet_is_female'            : int('female' in gender),
        'pref_age_kitten_puppy'    : int('puppy' in pref_age or 'kitten' in pref_age),
        'pref_age_young'           : int('young' in pref_age),
        'pref_age_adult'           : int('adult' in pref_age),
        'pref_age_senior'          : int('senior' in pref_age),
        'pref_gender_male'         : int(pref_gender == 'male'),
        'pref_gender_female'       : int(pref_gender == 'female'),
        'tag_similarity'           : round(float(tag_sim), 6),
        'living_apartment'         : int('apartment' in living),
        'living_yard'              : int('yard' in living),
        'living_no_yard'           : int(living == 'house_no_yard'),
        'activity_relaxed'         : int(activity == 'relaxed'),
        'activity_moderate'        : int(activity == 'moderate'),
        'activity_high'            : int(activity in ['high', 'active']),
        'exp_first_time'           : int(exp == 'first_time'),
        'exp_experienced'          : int(exp in ['experienced', 'expert']),
        'has_kids'                 : has_kids,
        'has_other_pets'           : has_pets,
        'hours_0_3'                : int(hours in ['0_3', '0-3']),
        'hours_4_7'                : int(hours in ['4_7', '4-7']),
        'hours_8_plus'             : int(hours in ['8_plus', '8+', '8plus']),
        'special_care_cap'         : sp_cap,
        'pet_special_need'         : sp_need,
    }

    for i, tag in enumerate(ALL_TEMPERAMENT_TAGS):
        row[f'adopter_tag_{tag.lower()}'] = desired_vec[i]
    for i, tag in enumerate(ALL_TEMPERAMENT_TAGS):
        row[f'pet_tag_{tag.lower()}'] = pet_vec[i]

    return row, tag_sim, pet_tags_list, color_match_score, age_match_score, gender_match_score, lifestyle_normalized


# ---------------------------------------------------------
# Match Reason Generator (Prioritizes Color, Age, Gender)
# ---------------------------------------------------------
def _generate_reasons(adopter_profile, pet, pet_tags_list, tag_sim,
                      color_match_score, age_match_score, gender_match_score):
    if not isinstance(adopter_profile, dict):
        adopter_profile = {}

    reasons = []
    tags_lower = [t.lower() for t in pet_tags_list]
    pref_col    = str(adopter_profile.get('preferred_color', 'any')).lower().strip()
    pref_age    = str(adopter_profile.get('preferred_age', 'any')).lower().strip()
    pref_gender = str(adopter_profile.get('preferred_gender', 'any')).lower().strip()
    
    living   = str(adopter_profile.get('living_environment', '')).lower()
    activity = str(adopter_profile.get('activity_level', '')).lower()
    exp      = str(adopter_profile.get('pet_experience', '')).lower()
    has_kids = bool(adopter_profile.get('has_children', False))
    has_pets = bool(adopter_profile.get('has_other_pets', False))
    hours    = str(adopter_profile.get('hours_alone', '')).lower()
    sp_cap   = bool(adopter_profile.get('special_care_capacity', False) or adopter_profile.get('special_care_capability', False))

    # 1. PRIMARY TIER: Color, Age, Gender matches first
    if pref_col not in ['any', 'all', '', 'any color'] and color_match_score >= 0.75:
        reasons.append(f"Matches your preferred {pet.get('color', 'coat')} color")

    if pref_age not in ['any', 'all', '', 'any age'] and age_match_score >= 0.75:
        reasons.append(f"Matches your desired {pet.get('age', 'age')} group")

    if pref_gender not in ['any', 'all', '', 'any gender'] and gender_match_score >= 0.75:
        gender_display = str(pet.get('gender', 'gender')).capitalize()
        reasons.append(f"Matches your preferred {gender_display} gender")

    # 2. SECONDARY TIER: Temperament alignment
    if tag_sim >= 0.65:
        matching_tags = [t for t in pet_tags_list if t in adopter_profile.get('desired_temperaments', [])]
        if matching_tags:
            reasons.append(f"Shares your preferred traits ({', '.join(matching_tags[:2])})")
        else:
            reasons.append("High temperament compatibility with your personality")

    # 3. TERTIARY TIER: Lifestyle & Capability
    if 'apartment' in living and ('calm' in tags_lower or 'independent' in tags_lower or str(pet.get('type', '')).lower() == 'cat'):
        reasons.append("Well-suited for apartment or condo living")
    elif 'yard' in living and ('energetic' in tags_lower or 'playful' in tags_lower):
        reasons.append("Thrives in a home with yard space for play")

    if activity in ['high', 'active'] and ('energetic' in tags_lower or 'playful' in tags_lower):
        reasons.append("Great energy match for your active routine")
    elif activity == 'relaxed' and ('calm' in tags_lower or 'affectionate' in tags_lower):
        reasons.append("Gentle and calm companion for a relaxed home")

    if exp == 'first_time' and ('friendly' in tags_lower or 'calm' in tags_lower):
        reasons.append("Great choice for first-time pet owners")

    if has_kids and ('friendly' in tags_lower or 'playful' in tags_lower):
        reasons.append("Friendly and safe around children")

    if has_pets and ('friendly' in tags_lower or 'playful' in tags_lower):
        reasons.append("Friendly and tested safe with other pets")

    if hours in ['8_plus', '8+'] and ('independent' in tags_lower or 'calm' in tags_lower):
        reasons.append("Independent personality comfortable during work hours")

    med_hist = str(pet.get('medical_history', '')).lower()
    if any(k in med_hist for k in ['special', 'chronic', 'amputee', 'blind', 'deaf', 'disabilit']) and sp_cap:
        reasons.append("Matches your willingness to provide special care")

    return reasons[:3] if reasons else ["Good overall compatibility with your profile"]


# ---------------------------------------------------------
# Main Recommendation Function
# ---------------------------------------------------------
def recommend_pets(pets_data, adopter_profile, top_k=20):
    """
    Returns ranked pet recommendations using the trained Random Forest model.
    Enforces strict weighting hierarchy:
      Color (22%) + Age (20%) + Gender (20%) = 62% > Temperament (19%) + Capability (19%) = 38%
    """
    if not pets_data:
        return []

    if not isinstance(adopter_profile, dict):
        adopter_profile = {}

    # Available pets only
    available = [p for p in pets_data if str(p.get('status', 'available')).lower() == 'available']
    if not available:
        available = pets_data

    # Strict species filtering
    pref_species = str(adopter_profile.get('preferred_species', 'any')).lower()
    if pref_species in ['dog', 'cat']:
        filtered = [p for p in available if str(p.get('type', '')).lower() == pref_species]
        if not filtered:
            return []
        available = filtered

    # Try trained model first
    model, feature_cols = _load_model()
    results = []

    for pet in available:
        row, tag_sim, pet_tags_list, col_score, age_score, gen_score, life_score = _build_feature_row(adopter_profile, pet)

        # Composite Demographics + Temperament + Capability Weighted Score (0.0 to 1.0)
        # Color: 22%, Age: 20%, Gender: 20%, Temperament: 19%, Capability: 19%
        composite_score = (
            (0.22 * col_score) +
            (0.20 * age_score) +
            (0.20 * gen_score) +
            (0.19 * tag_sim) +
            (0.19 * life_score)
        )

        if model is not None and feature_cols is not None:
            # Random Forest Inference
            feat_df = pd.DataFrame([[row.get(col, 0) for col in feature_cols]], columns=feature_cols)
            proba = model.predict_proba(feat_df)[0]
            rf_prob = float(proba[1])
            # Blend RF probability with composite formula to strictly enforce 62% demographic priority
            final_metric = (0.55 * rf_prob) + (0.45 * composite_score)
            algorithm_name = 'Random Forest Classifier (Color/Age/Gender Prioritized)'
        else:
            final_metric = composite_score
            algorithm_name = 'Multi-Attribute Scoring Engine (Color/Age/Gender Prioritized)'

        match_pct = round(min(99.0, max(50.0, (final_metric * 48.0) + 51.0)), 1)
        reasons = _generate_reasons(adopter_profile, pet, pet_tags_list, tag_sim,
                                    col_score, age_score, gen_score)

        photo_path = pet.get('photo_path', '')
        photo_url  = (
            photo_path if str(photo_path).startswith('http')
            else ('storage/' + photo_path.lstrip('/') if photo_path else '')
        )

        results.append({
            'pet_id'                 : pet['id'],
            'name'                   : pet.get('name', f"Pet no. {pet['id']}"),
            'type'                   : pet.get('type', 'dog'),
            'breed'                  : pet.get('breed', 'Mixed Breed'),
            'age'                    : pet.get('age', 'Unknown'),
            'gender'                 : pet.get('gender', 'Unknown'),
            'color'                  : pet.get('color', 'N/A'),
            'photo_path'             : photo_path,
            'photo_url'              : photo_url,
            'image'                  : photo_url,
            'status'                 : pet.get('status', 'available'),
            'description'            : pet.get('description', 'Loving rescue pet looking for a forever home.'),
            'medical_history'        : pet.get('medical_history', 'No medical history recorded.'),
            'match_percentage'       : match_pct,
            'temperament_similarity' : round(tag_sim * 100, 1),
            'temperaments'           : pet_tags_list,
            'temperament'            : pet_tags_list,
            'match_reasons'          : reasons,
            'algorithm'              : algorithm_name,
        })

    results.sort(key=lambda x: x['match_percentage'], reverse=True)
    return results[:top_k]


# ---------------------------------------------------------
# Entry point
# ---------------------------------------------------------
if __name__ == '__main__':
    raw = sys.stdin.read().strip()
    if not raw:
        print(json.dumps({'error': 'No input received'}))
        sys.exit(1)

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as e:
        print(json.dumps({'error': f'JSON parse error: {str(e)}'}))
        sys.exit(1)

    pets_data       = payload.get('pets', [])
    adopter_profile = payload.get('adopter_profile', {})
    if not isinstance(adopter_profile, dict):
        adopter_profile = {}

    recommendations = recommend_pets(pets_data, adopter_profile)

    output = {
        'success'        : True,
        'algorithm'      : 'Random Forest Classifier - Scikit-Learn (Color, Age, Gender Prioritized)',
        'count'          : len(recommendations),
        'recommendations': recommendations,
    }

    print(json.dumps(output, ensure_ascii=False))