# -*- coding: utf-8 -*-
"""
CAWS Pet Adoption System - Real-Time Pet Recommendation Engine
Algorithm  : Random Forest Classifier (Trained) + Cosine Similarity Fallback
Framework  : Scikit-Learn, Pandas, NumPy, Joblib
Model File : ml/pet_match_model.pkl  (generated by ml/train_model.py)
"""

import os
import sys

# Ensure ML packages (scikit-learn, joblib, pandas, numpy) are always found
# even when called as a subprocess from Laravel (which may strip user PATH/PYTHONPATH).
_user_site = os.path.join(os.path.expanduser('~'),
                          'AppData', 'Roaming', 'Python', 'Python314', 'site-packages')
if _user_site not in sys.path:
    sys.path.insert(0, _user_site)


import json
import joblib
import numpy as np
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics.pairwise import cosine_similarity


# ---------------------------------------------------------
# Constants
# ---------------------------------------------------------
ALL_TEMPERAMENT_TAGS = [
    'Friendly', 'Calm', 'Energetic', 'Shy',
    'Playful', 'Independent', 'Affectionate', 'Protective'
]

TAG_INDEX = {t: i for i, t in enumerate(ALL_TEMPERAMENT_TAGS)}

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH    = os.path.join(SCRIPT_DIR, 'pet_match_model.pkl')
FEATURES_PATH = os.path.join(SCRIPT_DIR, 'feature_columns.json')

# ---------------------------------------------------------
# Load trained model (once at startup)
# ---------------------------------------------------------
_trained_model   = None
_feature_columns = None

def _load_model():
    global _trained_model, _feature_columns
    if _trained_model is None and os.path.exists(MODEL_PATH) and os.path.exists(FEATURES_PATH):
        _trained_model   = joblib.load(MODEL_PATH)
        with open(FEATURES_PATH, 'r') as f:
            _feature_columns = json.load(f)
    return _trained_model, _feature_columns


# ---------------------------------------------------------
# Feature Engineering
# ---------------------------------------------------------
def _build_feature_row(adopter_profile, pet):
    """
    Converts an adopter profile + one pet into the same
    39-column feature vector used during training.
    """
    living   = str(adopter_profile.get('living_environment', 'apartment')).lower()
    activity = str(adopter_profile.get('activity_level', 'moderate')).lower()
    exp      = str(adopter_profile.get('pet_experience', 'first_time')).lower()
    has_kids = int(bool(adopter_profile.get('has_children', False)))
    has_pets = int(bool(adopter_profile.get('has_other_pets', False)))
    hours    = str(adopter_profile.get('hours_alone', '4_7')).lower()
    sp_cap   = int(bool(adopter_profile.get('special_care_capability', False)))
    pref_col = str(adopter_profile.get('preferred_color', 'any')).lower()

    desired_tags_list = [t for t in adopter_profile.get('desired_temperaments', [])
                         if t in ALL_TEMPERAMENT_TAGS]
    desired_vec = [1 if t in desired_tags_list else 0 for t in ALL_TEMPERAMENT_TAGS]

    # Pet side
    species  = str(pet.get('type', 'dog')).lower()
    age_raw  = str(pet.get('age', 'adult')).lower()
    if any(k in age_raw for k in ['kitten', 'puppy', '0', '1']):
        age_cat = 'kitten_puppy'
    elif any(k in age_raw for k in ['young', 'junior', '2', '3']):
        age_cat = 'young'
    elif any(k in age_raw for k in ['senior', 'old', '8', '9', '10', '11', '12']):
        age_cat = 'senior'
    else:
        age_cat = 'adult'

    color      = str(pet.get('color', '')).lower()
    med_hist   = str(pet.get('medical_history', '')).lower()
    sp_need    = int(any(k in med_hist for k in ['special', 'chronic', 'amputee', 'blind', 'deaf']))

    pet_tags_list = [t for t in pet.get('temperaments', []) if t in ALL_TEMPERAMENT_TAGS]
    pet_vec = [1 if t in pet_tags_list else 0 for t in ALL_TEMPERAMENT_TAGS]

    # Tag similarity (used as a feature)
    d_arr = np.array(desired_vec, dtype=float)
    p_arr = np.array(pet_vec, dtype=float)
    d_mag = np.linalg.norm(d_arr)
    p_mag = np.linalg.norm(p_arr)
    tag_sim = float(np.dot(d_arr, p_arr) / (d_mag * p_mag)) if d_mag > 0 and p_mag > 0 else 0.5

    color_matched = int(pref_col in ['any', ''] or pref_col in color)

    row = {
        'living_apartment' : int('apartment' in living),
        'living_yard'      : int('yard' in living),
        'living_no_yard'   : int(living == 'house_no_yard'),
        'activity_relaxed' : int(activity == 'relaxed'),
        'activity_moderate': int(activity == 'moderate'),
        'activity_high'    : int(activity in ['high', 'active']),
        'exp_first_time'   : int(exp == 'first_time'),
        'exp_experienced'  : int(exp in ['experienced', 'expert']),
        'has_kids'         : has_kids,
        'has_other_pets'   : has_pets,
        'hours_0_3'        : int(hours in ['0_3', '0-3']),
        'hours_4_7'        : int(hours in ['4_7', '4-7']),
        'hours_8_plus'     : int(hours in ['8_plus', '8+', '8plus']),
        'special_care_cap' : sp_cap,
        'is_dog'           : int(species == 'dog'),
        'is_cat'           : int(species == 'cat'),
        'age_kitten_puppy' : int(age_cat == 'kitten_puppy'),
        'age_young'        : int(age_cat == 'young'),
        'age_adult'        : int(age_cat == 'adult'),
        'age_senior'       : int(age_cat == 'senior'),
        'pet_special_need' : sp_need,
        'tag_similarity'   : round(tag_sim, 6),
        'color_matched'    : color_matched,
    }

    for i, tag in enumerate(ALL_TEMPERAMENT_TAGS):
        row[f'adopter_tag_{tag.lower()}'] = desired_vec[i]
    for i, tag in enumerate(ALL_TEMPERAMENT_TAGS):
        row[f'pet_tag_{tag.lower()}'] = pet_vec[i]

    return row, tag_sim, pet_tags_list


# ---------------------------------------------------------
# Match Reason Generator
# ---------------------------------------------------------
def _generate_reasons(adopter_profile, pet, pet_tags_list, tag_sim):
    reasons = []
    living   = str(adopter_profile.get('living_environment', '')).lower()
    activity = str(adopter_profile.get('activity_level', '')).lower()
    exp      = str(adopter_profile.get('pet_experience', '')).lower()
    pref_col = str(adopter_profile.get('preferred_color', 'any')).lower()
    has_kids = bool(adopter_profile.get('has_children', False))
    hours    = str(adopter_profile.get('hours_alone', '')).lower()
    sp_cap   = bool(adopter_profile.get('special_care_capability', False))

    tags_lower = [t.lower() for t in pet_tags_list]

    if tag_sim >= 0.80:
        reasons.append("Excellent personality alignment with your preferences")
    elif tag_sim >= 0.50:
        reasons.append("Good temperament match with your lifestyle")

    if 'apartment' in living and ('calm' in tags_lower or 'independent' in tags_lower):
        reasons.append("Well-suited for apartment or indoor living")
    if 'yard' in living and ('energetic' in tags_lower or 'playful' in tags_lower):
        reasons.append("Loves the outdoor space your home provides")

    if activity in ['high', 'active'] and ('energetic' in tags_lower or 'playful' in tags_lower):
        reasons.append("Matches your active and energetic lifestyle")
    elif activity == 'relaxed' and 'calm' in tags_lower:
        reasons.append("Perfectly suited for your calm and relaxed home")

    if exp == 'first_time' and ('friendly' in tags_lower or 'calm' in tags_lower):
        reasons.append("Great choice for first-time pet owners")

    if has_kids and ('friendly' in tags_lower or 'playful' in tags_lower):
        reasons.append("Friendly and safe around children")

    if hours in ['8_plus', '8+'] and ('independent' in tags_lower or 'calm' in tags_lower):
        reasons.append("Independent personality comfortable during work hours")

    if pref_col not in ['any', ''] and pref_col in str(pet.get('color', '')).lower():
        reasons.append(f"Matches your preferred {pet.get('color', '')} color")

    med_hist = str(pet.get('medical_history', '')).lower()
    if any(k in med_hist for k in ['special', 'chronic', 'amputee', 'blind', 'deaf']) and sp_cap:
        reasons.append("Matches your willingness to provide special care")

    return reasons[:3] if reasons else ["Good overall compatibility with your profile"]


# ---------------------------------------------------------
# Main Recommendation Function
# ---------------------------------------------------------
def recommend_pets(pets_data, adopter_profile, top_k=20):
    """
    Returns ranked pet recommendations using the trained Random Forest model.
    Falls back to cosine similarity if model file is unavailable.
    """
    if not pets_data:
        return []

    # Available pets only
    available = [p for p in pets_data if str(p.get('status', 'available')).lower() == 'available']
    if not available:
        available = pets_data

    # Strict species filtering
    pref_species = str(adopter_profile.get('preferred_species', 'any')).lower()
    if pref_species in ['dog', 'cat']:
        filtered = [p for p in available if str(p.get('type', '')).lower() == pref_species]
        if not filtered:
            return []
        available = filtered

    # Try trained model first
    model, feature_cols = _load_model()

    results = []

    if model is not None and feature_cols is not None:
        # ---- Trained Random Forest inference ----
        for pet in available:
            row, tag_sim, pet_tags_list = _build_feature_row(adopter_profile, pet)

            # Align to training feature order using a DataFrame (preserves feature names)
            feat_df = pd.DataFrame([[row.get(col, 0) for col in feature_cols]], columns=feature_cols)

            # predict_proba returns [P(incompatible), P(compatible)]
            proba        = model.predict_proba(feat_df)[0]
            compat_prob  = float(proba[1])                          # probability of "Compatible"
            match_pct    = round(min(99.0, max(55.0, compat_prob * 100.0)), 1)

            reasons = _generate_reasons(adopter_profile, pet, pet_tags_list, tag_sim)

            photo_path = pet.get('photo_path', '')
            photo_url  = (
                photo_path if str(photo_path).startswith('http')
                else ('storage/' + photo_path.lstrip('/') if photo_path else '')
            )

            results.append({
                'pet_id'                 : pet['id'],
                'name'                   : pet.get('name', f"Pet no. {pet['id']}"),
                'type'                   : pet.get('type', 'dog'),
                'breed'                  : pet.get('breed', 'Mixed Breed'),
                'age'                    : pet.get('age', 'Unknown'),
                'gender'                 : pet.get('gender', 'Unknown'),
                'color'                  : pet.get('color', 'N/A'),
                'photo_path'             : photo_path,
                'photo_url'              : photo_url,
                'image'                  : photo_url,
                'status'                 : pet.get('status', 'available'),
                'description'            : pet.get('description', 'Loving rescue pet looking for a forever home.'),
                'medical_history'        : pet.get('medical_history', 'No medical history recorded.'),
                'match_percentage'       : match_pct,
                'temperament_similarity' : round(tag_sim * 100, 1),
                'temperaments'           : pet_tags_list,
                'temperament'            : pet_tags_list,
                'match_reasons'          : reasons,
                'algorithm'              : 'Random Forest Classifier (Trained Model)',
            })

    else:
        # ---- Cosine Similarity fallback (no .pkl file found) ----
        mlb = MultiLabelBinarizer(classes=ALL_TEMPERAMENT_TAGS)
        pet_tag_lists = [
            [t for t in p.get('temperaments', []) if t in ALL_TEMPERAMENT_TAGS]
            for p in available
        ]
        pet_matrix = mlb.fit_transform(pet_tag_lists)

        desired = [t for t in adopter_profile.get('desired_temperaments', [])
                   if t in ALL_TEMPERAMENT_TAGS]
        if not desired:
            desired = ['Friendly']
        adopter_vec = mlb.transform([desired])

        if pet_matrix.shape[1] > 0:
            sims = cosine_similarity(adopter_vec, pet_matrix)[0]
        else:
            sims = np.full(len(available), 0.5)

        for i, pet in enumerate(available):
            sim      = float(sims[i])
            match_pct = round(min(99.0, max(55.0, sim * 45.0 + 54.0)), 1)
            reasons   = _generate_reasons(adopter_profile, pet, pet_tag_lists[i], sim)

            photo_path = pet.get('photo_path', '')
            photo_url  = (
                photo_path if str(photo_path).startswith('http')
                else ('storage/' + photo_path.lstrip('/') if photo_path else '')
            )

            results.append({
                'pet_id'                 : pet['id'],
                'name'                   : pet.get('name', f"Pet no. {pet['id']}"),
                'type'                   : pet.get('type', 'dog'),
                'breed'                  : pet.get('breed', 'Mixed Breed'),
                'age'                    : pet.get('age', 'Unknown'),
                'gender'                 : pet.get('gender', 'Unknown'),
                'color'                  : pet.get('color', 'N/A'),
                'photo_path'             : photo_path,
                'photo_url'              : photo_url,
                'image'                  : photo_url,
                'status'                 : pet.get('status', 'available'),
                'description'            : pet.get('description', 'Loving rescue pet looking for a forever home.'),
                'medical_history'        : pet.get('medical_history', 'No medical history recorded.'),
                'match_percentage'       : match_pct,
                'temperament_similarity' : round(sim * 100, 1),
                'temperaments'           : pet_tag_lists[i],
                'temperament'            : pet_tag_lists[i],
                'match_reasons'          : reasons,
                'algorithm'              : 'Cosine Similarity (Fallback)',
            })

    results.sort(key=lambda x: x['match_percentage'], reverse=True)
    return results[:top_k]


# ---------------------------------------------------------
# Entry point (called by Laravel via stdin pipe)
# ---------------------------------------------------------
if __name__ == '__main__':
    raw = sys.stdin.read().strip()
    if not raw:
        print(json.dumps({'error': 'No input received'}))
        sys.exit(1)

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as e:
        print(json.dumps({'error': f'JSON parse error: {str(e)}'}))
        sys.exit(1)

    pets_data       = payload.get('pets', [])
    adopter_profile = payload.get('adopter_profile', {})

    recommendations = recommend_pets(pets_data, adopter_profile)

    output = {
        'success'        : True,
        'algorithm'      : 'Random Forest Classifier - Scikit-Learn (Trained Model)',
        'count'          : len(recommendations),
        'recommendations': recommendations,
    }

    print(json.dumps(output, ensure_ascii=False))
